// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "go-zero-demo/user-api/internal/handler/user"
	"go-zero-demo/user-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/info_get",
				Handler: user.UserInfoGetHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/info_get_rpc",
				Handler: user.UserInfoRpcGetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/info_post",
				Handler: user.UserInfoPostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/update",
				Handler: user.UpDateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/user/delete",
				Handler: user.DeleteUserHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
